# Generated by Django 4.2 on 2023-04-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='purchased_books',
            new_name='purchased_clothes',
        ),
    ]
