# Generated by Django 4.1.6 on 2023-02-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_films_alter_cityslocation_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cinemas',
            new_name='Cinema',
        ),
        migrations.RenameModel(
            old_name='CitysLocation',
            new_name='CityLocation',
        ),
    ]
